// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPuE4xs9rK4j1EktHUgv0LLj4Qu4e4dYQ',
    appId: '1:218578553229:web:b0fd267efbcd11848f55c4',
    messagingSenderId: '218578553229',
    projectId: 'folish-c1d90',
    authDomain: 'folish-c1d90.firebaseapp.com',
    storageBucket: 'folish-c1d90.firebasestorage.app',
    measurementId: 'G-3FM25PWP7Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkGZn5lxZrYt54HrF0hKWytuksnfONLTY',
    appId: '1:218578553229:android:8bdbc90c3ae170c48f55c4',
    messagingSenderId: '218578553229',
    projectId: 'folish-c1d90',
    storageBucket: 'folish-c1d90.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2_ropNESNr8XpOvEiBHt59gsUfzuRSH8',
    appId: '1:218578553229:ios:4ad12402459600f98f55c4',
    messagingSenderId: '218578553229',
    projectId: 'folish-c1d90',
    storageBucket: 'folish-c1d90.firebasestorage.app',
    iosBundleId: 'com.example.folish',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2_ropNESNr8XpOvEiBHt59gsUfzuRSH8',
    appId: '1:218578553229:ios:4ad12402459600f98f55c4',
    messagingSenderId: '218578553229',
    projectId: 'folish-c1d90',
    storageBucket: 'folish-c1d90.firebasestorage.app',
    iosBundleId: 'com.example.folish',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPuE4xs9rK4j1EktHUgv0LLj4Qu4e4dYQ',
    appId: '1:218578553229:web:1c3ff3022b805f8f8f55c4',
    messagingSenderId: '218578553229',
    projectId: 'folish-c1d90',
    authDomain: 'folish-c1d90.firebaseapp.com',
    storageBucket: 'folish-c1d90.firebasestorage.app',
    measurementId: 'G-SGPQHM9Y34',
  );
}
